"use client";
import { useEffect,useMemo,useState } from "react";
import { api } from "../../../lib/api";
import DataTable from "../../../components/DataTable";
import {Button,Input,Select} from "../../../components/ui";
export default function Inventory(){
 const [items,setItems]=useState([]),[tx,setTx]=useState([]),[form,setForm]=useState({item_id:"",transaction_type:"STOCK_IN",quantity:"",from_location:"",to_location:"",notes:""}),[error,setError]=useState("");
 async function load(){const [a,b]=await Promise.all([api("/stock-items"),api("/inventory/transactions")]);setItems(a.items);setTx(b.items)} useEffect(()=>{load();if(new URLSearchParams(location.search).get("action")==="transfer"){setForm(x=>({...x,transaction_type:"TRANSFER"}));setTimeout(()=>document.querySelector("[data-inventory-item]")?.focus(),0)}},[]);
 async function save(e){e.preventDefault();setError("");try{await api("/inventory/transactions",{method:"POST",body:JSON.stringify(form)});setForm({...form,quantity:"",notes:""});load()}catch(e){setError(e.message)}}
 const cols=useMemo(()=>[{accessorKey:"name",header:"Item"},{accessorKey:"quantity",header:"Current Stock"},{accessorKey:"reserved_stock",header:"Reserved"},{accessorKey:"damaged_stock",header:"Damaged"},{accessorKey:"reorder_level",header:"Reorder"},{id:"available",header:"Available",cell:({row})=>Number(row.original.quantity)-Number(row.original.reserved_stock)},{id:"valuation",header:"Valuation",cell:({row})=>(Number(row.original.quantity)*Number(row.original.purchase_price)).toFixed(2)}],[]);
 return <><div className="mb-5"><h1 className="text-2xl font-bold">Inventory</h1><p className="text-sm text-slate-500">Stock in, stock out, adjustment, transfer, reservation and damage.</p></div><div className="card mb-6"><DataTable columns={cols} data={items}/></div>
 <form onSubmit={save} className="card mb-6 grid gap-4 p-5 md:grid-cols-3"><Select data-inventory-item autoFocus label="Item" value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})} required><option value="">Select</option>{items.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</Select><Select label="Transaction" value={form.transaction_type} onChange={e=>setForm({...form,transaction_type:e.target.value})}>{["STOCK_IN","STOCK_OUT","ADJUSTMENT","TRANSFER","DAMAGED","RESERVED"].map(x=><option key={x}>{x}</option>)}</Select><Input label="Quantity" type="number" step=".001" min=".001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} required/><Input label="From Location" value={form.from_location} onChange={e=>setForm({...form,from_location:e.target.value})}/><Input label="To Location" value={form.to_location} onChange={e=>setForm({...form,to_location:e.target.value})}/><Input label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>{error&&<p className="text-red-600 md:col-span-3">{error}</p>}<Button className="md:col-span-3">Post Inventory Transaction</Button></form>
 <div className="card"><h2 className="border-b p-4 font-bold">Stock Movement</h2><DataTable data={tx} columns={[{accessorKey:"transaction_date",header:"Date"},{accessorKey:"transaction_type",header:"Type"},{accessorKey:"item_id",header:"Item ID"},{accessorKey:"quantity",header:"Quantity"},{accessorKey:"from_location",header:"From"},{accessorKey:"to_location",header:"To"}]}/></div></>
}
